# Vanjski file s tajnama (izvan git repo-a, u parent mapi JavaWeb)
spring.config.import=optional:file:../application-secrets.properties

# Database
spring.datasource.url=${DB_URL}
spring.datasource.username=${DB_USERNAME}
spring.datasource.password=${DB_PASSWORD}
spring.datasource.driver-class-name=com.microsoft.sqlserver.jdbc.SQLServerDriver

# JPA
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=false
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.SQLServerDialect

# JWT
app.jwt.secret=${JWT_SECRET}
app.jwt.access-expiration-ms=900000
app.jwt.refresh-expiration-ms=604800000


app.base-url=${APP_BASE_URL:http://localhost:8080}
# PayPal
paypal.client.id=${PAYPAL_CLIENT_ID}
paypal.client.secret=${PAYPAL_CLIENT_SECRET}
paypal.mode=sandbox

# RAWG
rawg.api.key=${RAWG_API_KEY}
rawg.api.base-url=https://api.rawg.io/api

# Async
spring.task.execution.pool.core-size=5
spring.task.execution.pool.max-size=10

# Thymeleaf
spring.thymeleaf.cache=false

# EMAIL CONFIGURATION
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=em4ncipor@gmail.com
spring.mail.password=${MAIL_PASSWORD}
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true



server.port=8080
